### ISSUE TITLE
Don't respond in Chrome

### ISSUE THREAD

**Issue by 1Timo1** [olejon/spotcommander#107]
When i use Google Chrome it don't respond to any action.

Sorry for my bad english <3

**Comment by olejon** [comment]
Google Chrome on a PC, right? If your PC supports touch, then SpotCommander will only work if you touch the screen. Keyboard and mouse will not work. This because there is still very hard to code webapps that uses **responsive** touch feedback and gestures and support keyboard and mouse at the same time, because they don't send the same signals to the webapp (touch events vs click events). Microsoft tried to solve this with their Pointer Events proposal. Unfortunately Google, Apple, Mozilla etc. decided not to implement it, primarily Apple, which developed WebKit, which Chrome's engine is based on, although now they develop separate from Apple. WebKit is again based on KHTML (KDE's previous browser), so Apple decided to keep WebKit as a open source software project. Chrome is still very much a WebKit-based browser, but they now develop their engine on their own (Chromium), and not just use Apple's engine, to try to make a faster browser than Safari. Since both WebKit and Chromium are open source they now borrow code from each other.

If you **don't** use the touch screen in Google Chrome, you can disable touch events and then SpotCommander will not detect touch support and mouse and keyboard will work. See here how to do it:

http://ccm.net/faq/40811-google-chrome-how-to-disable-touch-input

(After changing a flag make sure to click the button that appears to restart Chrome).

Another solution is to just use touch :-)

**Comment by 1Timo1** [comment]
I don't have touch and I'm on Windows yes

Am 20.10.2016 17:03 schrieb "Ole Jon Bjørkum" <notifications@github.com>:

**Comment by olejon** [comment]
Does it work in another browser like Internet Explorer or Firefox?

**Comment by 1Timo1** [comment]
Yes works with Firefox and Edge.
A Friend has the same chrome version and it works also.

Am 20.10.2016 19:55 schrieb "Ole Jon Bjørkum" <notifications@github.com>:

Does it work in another browser like Internet Explorer or Firefox?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/olejon/spotcommander/issues/107#issuecomment-255179854>,
or mute the thread

**Comment by olejon** [comment]
Type `chrome://flags/#touch-events` in the URL bar in Chrome and choose `Disabled` in the drop down list. Then press the button that appears to restart Chrome, and see if it works.

**Comment by olejon** [comment]
Closed due to no response. Re-open if any news.

**Comment by nebulade** [comment]
It seems to work fine if the variable `ua_supports_touch` at https://github.com/olejon/spotcommander/blob/master/spotcommander/js/main.js#L48 is set to `false`

Not sure if this could be made a settings variable to override the detection?

**Comment by olejon** [comment]
Then it only supports keyboard and mouse, yes.

I have already in the code that Chromebooks (user agent contains `CrOS`) will not use touch although they support it because at the early stages nobody used touch on Chromebooks (it was experimental), or in Chrome in general really, as it touch was really bad.

I could make it a Setting yes. Will keep this issue open.

If you don't use touch at all, and use Chrome you can disable touch completely in chrome://flags

You can also launch SpotCommander as a desktop app without any browser chrome (address bar etc) and with touch disabled like this:

`google-chrome --touch-events=disabled --app=http://computer/spotcommander/`

or

`google-chrome --app=http://computer/spotcommander/ --touch-events=disabled`

If you use Chromium use the command to launch `chromium` command instead of `google-chrome`.

Think that should work, but can not test it with the equipment I have now.

Let me know if it works and I can tell you how to create a desktop shortcut so you can easily launch it from your Applications Menu.

See code for touch:

https://github.com/olejon/spotcommander/blob/master/spotcommander/js/main.js#L48

Also changing this line to:

ua_supports_touch = (!Modernizr.touchevents && !shc(ua, 'CrOS'));

... will disable touch, and make it easier to go back.

If you know some JS you can easily make a switch wherever you want in your installation, or even just run JS code in the address bar to set the variable to `true` or `false`.

**Comment by olejon** [comment]
Edited a little...

**Comment by nebulade** [comment]
Yeah I have put some code locally, that's why I  came here to reply, works well. I use firefox though, where one can also disable touch events, however I need them enabled for other development work. Maybe I find some time to come up with some pull request though...

**Comment by olejon** [comment]
Issue really duplica to issue #126

**Comment by olejon** [comment]
Don't worry about a commit. I can easily fix it myself, using my style of doing things regarding settings.

**Comment by olejon** [comment]
What about a Application Menu entry like this:

```
[Desktop Entry]
Type=Application
Name=SpotCommander
Exec=google-chrome --touch-events=disabled --app=http://computer/spotcommander/
Icon=/usr/share/spotcommander/img/favicon-192.png
```
