### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Poussinou** [olejon/spotcommander#108]
Any possibility to translate this amazing app in French? (In the "res" folder I suppose)

**Comment by olejon** [comment]
99 % of SpotCommander is the web app. The Android app is only a kind of custom browser that gives Android users extra features. So translating the Android app would not make much sense. Unfortunately the strings in the web app (main app) are hard coded. I did not expect more than 50,000 downloads only on Google Play when I started the project, so that is why. And I have had very few requests to translate the app, and because it would require much work since all the strings are hard coded it can not be a priority.

As you probably know you can access SpotCommander from every device, like from your computer using a modern browser, like Chrome or Firefox, and to to http://your.computer/spotcommander/

**Comment by Poussinou** [comment]
Ok no problem ;)
thanks for this great app
