### ISSUE TITLE
Play All button disappeared on Galaxy Tab 4

### ISSUE THREAD

**Issue by sparksy777** [olejon/spotcommander#117]
The latest version of the Android app replaces the 'Play all' menu option with a material design button that floats over a list of tracks (playlist, album, etc).

This button works fine on my smartphone running Android 7, but the button doesn't appear on my Galaxy Tab 4 tablet running Android 5.0.4 . Strangely, I believe I saw the button the first time I ran the upgraded app on my tablet, but only once. It did not reappear even after restarting my device.

If the button is erratic, maybe it would be worth keeping a 'Play all' option in the menu .

Awesome app, BTW.

**Comment by olejon** [comment]
That's weird. I suppose it appears in various desktop web browsers for example?

In the meantime you can tap on a track in the list and play it and it should play the list if you have Premium. If not you must queue tracks.

**Comment by sparksy777** [comment]
Even weirder: the button has now returned! I've not been able to get my tablet to repeat the strange behaviour, I'll let you know if it happens again.

Thanks for the quick response, I can see why you  have only three open issues in here. This is an amazingly stable app given all the quirks of Android, Linux and Spotify. I'd struggled with Spotify remote control for years before I discovered this app. I even considered loading Windows onto my HTPC to get it to work; thanks for saving me from that!

**Comment by olejon** [comment]
Everything to save someone from Windows when possible ;)

**Comment by sparksy777** [comment]
BTW, the disappearing button issue occurred again a moment ago, and it turns out the button has not disappeared, it is merely invisible. When I tapped the screen at the point the button was supposed to be, the button reappeared.

**Comment by olejon** [comment]
Do you have the latest Android System WebView installed?

https://play.google.com/store/apps/details?id=com.google.android.webview

Also is there no system update to at least Android 5.1? In the Android Emulator WebView simply crashes when testing on 5.0. I suppose I could check in GenyMotion, more likely to work there, if 5.0 is available in their selection. Anyway going to Spain in 30 mins so must be later :)

**Comment by sparksy777** [comment]
Ah, genius. I have a backlog of app updates to do, and yes, there is a WebView update waiting for me. Hopefully that will fix it, enjoy your vacation!

Phil.

**Comment by olejon** [comment]
Thanks. Maybe you must disable Samsung's WebView, if not using a package name Android overrides, I don't know but Samsung messes with everything, especially before. In Settings > Apps > Find Samsung WebView > Disable > Reboot.

This may break the Samsung Browser but Google Chrome man... The Android System WebView uses the same engine and version as Google Chrome, and is updated at the same time as since 4.4 Android WebView can be updated from Google Play. That's why it's though to develop an Android app with a WebView with some newer HTML5 features on Android older than 4.4. Have to use feature detection and use other code (double code) if WebView is too old. Another maybe bigger disadvantage is that many older than 4.4 don't support newer HTTPS certificates and the site won't open (unless the browser gives you the possibility to do so, but it's insecure), because Certificate Authorities are updated with browsers. A WebView is a browser, just with an API. The stock Android Browser on older Android versions before Chrome became default uses System WebView and builds a GUI around it and all the behavior the WebView API offers.

It was really a stupid stupid thing to ship stock Android with a WebView that didn't update (before 4.4), as many manufacturers didn't update their systems as you know... So usually browser on device stuck with security holes and what not if not using Chrome, Firefox etc.

Luckily Google has a stricter policy now regarding updates, how long manufacturers must update, and most system components can be updated by Google Play Services and apps through Google Play Store. On Android 7 and newer the default implementation is to use Chrome Stable as WebView. You don't need the separate app. This can be changed in Developer Settings (if enabled), to Chrome Beta etc, or even the separate app if you install it.

**Comment by olejon** [comment]
Any news on this?

**Comment by sparksy777** [comment]
Thanks for checking in. I couldn't find the Samsung Web View to disable it,
and the intermittent invisible button glitch is still occurring. I can live
with the bug now that I know where to press on the screen, but maybe adding
Play All item in the menu would help others if this is bug is found
elsewhere.

I don't have any outstanding issues if you would like to close this ticket.
Thanks for all your help!

Phil

**Comment by olejon** [comment]
So no Android update? You did install the Android System WebView from the Store right?

**Comment by olejon** [comment]
Closing due to no response. Workaround works.
