### ISSUE TITLE
SpotCommander - Queue - Premium - Ubuntu 17.04

### ISSUE THREAD

**Issue by LoyCog** [olejon/spotcommander#118]
With this new version I have noticed a major problem. 
Previously when I queue song from Spotcommander web panel, song was played next and then original spotify queue continued to play. Now when queued song starts to play I noticed that spotify queue is cleared and only this 1 song is in queue. After it have ended, spotify stops. Is this a bug or there is some configuration options that I have missed?

**Comment by olejon** [comment]
Let me ask you a question first:

1. Do you have Spotify Premium?

**Comment by LoyCog** [comment]
Yes

**Comment by olejon** [comment]
OK. The problem is that one can not pass `context_uri` (artists, albums and playlists) to together with the `uris` paramtere to the new Spotify `player` Web API. So yes, when only one URI is `PUT` to the API (last track in Queue), it will repeat over and over again as it overrides the entire "what was playing". This is a enhancement I have filed to Spotify, but probably they will release a Queue API soon, I hope, many have requested this so...

In the meantime I can make a workaround for the next version, that the artist/album/playlist that was playing before, will be played after the last track in Queue. But if I can pull off playing from the same position I do not know. I am on vacation in my second home now, Spain. If you toggle to "Repeat all" for instance it will play that last track over and over, since the `player` API with `uris` is more or less a type of Queue. I have it on my to-do list :)

**Comment by LoyCog** [comment]
This feature is really important to me. Basically I am forced not to use spotcommander if the spotify queue is wiped every time someone queues song from web panel. Is there some dirty hack possible to get it working now? Can't wait for next release.

**Comment by olejon** [comment]
Well I can think of two solutions:

* Disable Premium features in the file `config.php` and Downgrade to Spotify v 0.9 (instructions on the wiki)
* Create a playlist and use it as Queue. Toggle shuffle off and add tracks to that playlist and play it

**Comment by LoyCog** [comment]
Can't figure out how to downgrade spotify on Ubuntu 17. Following wiki I can't install libgcrypt11.

**Comment by olejon** [comment]
As I write on the Requirements and Downgrade pages on the wiki, I only support LTS versions of Ubuntu, that is now 14.04 and 16.04, and the Debian versions they are based on. Probably downgrading to v 0.9 won't work on the latest versions of Ubuntu no. Maybe I can find a fix, have to test in a Virtual Machine. After vacations. Use the playlist solution then.

**Comment by olejon** [comment]
Maybe you can Downgrade if you extract the libgcrypt deb and put the needed `.so` files in the correct directory. It won't overwrite anything as later Ubuntu versions use libgcrypt20.

**Comment by olejon** [comment]
I managed to install *Spotify v 0.9* on Ubuntu 17.04 by doing this:

```
wget -N http://security.ubuntu.com/ubuntu/pool/main/libg/libgcrypt11/libgcrypt11_1.5.3-2ubuntu4.5_amd64.deb
wget -N http://repository.spotify.com/pool/non-free/s/spotify/spotify-client-0.9.17_0.9.17.8.gd06432d.31-1_amd64.deb
sudo dpkg -i --force-all libgcrypt11_1.5.3-2ubuntu4.5_amd64.deb
sudo dpkg -i --force-all spotify-client-0.9.17_0.9.17.8.gd06432d.31-1_amd64.deb
```

Remember to disable Premium features as described above, in `/usr/share/spotcommander/config.php`

Please tell me if it works or not!

**Comment by LoyCog** [comment]
That worked!
Had to remove previous lib with 
`sudo dpkg -r libgcrypt11:i386`

Thanks for great support.

**Comment by olejon** [comment]
Good!
