### ISSUE TITLE
Devices no longer findable

### ISSUE THREAD

**Issue by balloch** [olejon/spotcommander#125]
It looks like this fix disables spotify connect, IE spotify will still tell me if it is playing a streamed song on another device, and I can switch that streamed song back to my Ubuntu machine, but then after I do that device disappears from the device list. When I use a streaming song to select a device and then try to play the local song, it just refuses.

**Comment by olejon** [comment]
Are you referring to issue #119 ?

**Comment by balloch** [comment]
No, unfortunately I have noticed that devices only show up when they are playing somewhere else in the network and then disappear if they stop playing, and local files will not play on any of these devices

**Comment by olejon** [comment]
What devices disappear?

First of all Spotify removed the possibility (bug or just cleanup) in v 1.0 of the Spotify client to play local files through MPRIS as they changed the behaviour in a way many have complained about to Spotify. Especially OpenUri() on a song will repeat the song over and over instead of resuming where it was like on Spotify 0.9, and local files don’t play anymore using that function, so no workaround for that. That’s why I recommend v 0.9 to users who don’t have premium, as playing a single track just repeats it which also means the queue doesn’t work (first song over and over). Really MPRIS is just there to support like the Ubuntu Sound Menu and such, which only needs Play/Pause and Skip. But many third part scripts etc uses the OpenUri() which works, and perfectly until Spotify 1.0. Pretty lucky it’s even implemented as they have maybe just implemented 10 % of the D-Bus MPRIS API. Like no shuffle, repeat or volume control for instance. For non-Premium users I must use hacks for that (PulseAudio and Keyboard Shortcuts simulation, hacky...).

The Player API does not accept local file URIs, they are like `spotify:local:urlEncodedAristAlbumAndTrackName:Number`, so nothing to do there. Understandable somehow as local files can be different on different  devices, but it could at least try since the URI contains some info. Songs on Spotify have a unique URI.

I haven’t done much testing with the Player API and switching to and from devices mixing between the API and Spotify Connect, which is not open with more features for third party speakers etc.

Anyway IIRC on an iPhone or iPad, if closing the app (not from multitasking, just going to home screen or another app) will make it invisible to the API. This because an iOS app can only do a few seconds of work when closed to save a document for instance. Background App Refresh, if enabled, doesn’t help either as it’s meant for content updates. If you open an app often (and it is in the multitasking menu, not killed) it is allowed, in power saving intervals, to check for new data, for example Facebook, so the feed is updated when you open the app again. If killed by the system because of lack of RAM I’m not sure if it has this priority anymore as you then obviously use other apps more. Because it can only do work at intervals it can’t tell the API “I’m here” if asked. One can use push notifications to any app and it appears immediately as you know, but that doesn’t mean the app can reply back every time. ExceptIons for full multitasking are Apple’s own apps, video/chat apps, navigation apps and **music apps playing at the moment**, obviously they won’t be killed by lack of RAM but have priority. IIRC correctly the iOS app only appears in the API, that is SpotCommander, when open. I think screen can be turned off but then music must be playing, IIRC. If playing music and going to another app, I don’t remember. Can’t test right now. But I remember when my girlfriend started playing on her iPhone, although on cellular far away (we have same account), **it did turn up in Devices** when I went to check to see why my playback stopped. So I think SpotCommander will show any iOS device currently playing, but not if not playing unless the app is open with screen on and maybe a while after screen off with the app currently the open and active one.

Android is more powerful, **up until Android 8**, where an app can run a “sticky” background service, and Spotify calls this “HelperService”, that’s why you see suddenly now playing notification from the Spotify app if starting to play on another device. This uses Spotify Connect. IIRC the Android app did not disappear from Devices just by going out of the app, but maybe after a while. If removed from the multitasking menu or not playing and killed because of lack of RAM, the “HelperService” will restart ASAP since it’s “sticky”, it uses little memory when the app is not in cache, or saying, open or in the multitasking menu, so it normally isn’t killed unless the app is open, but not the active one, and not playing. **But sticky services are not supported on Android 8 or newer** unless they show a foreground notification to let the user know an app is running in the background. Only system apps can do this, or an app can request “Ignore optimisations”, but Google warns this should *only be used when absolutely necessary *. On Android < 8 it uses the same behaviour as always, and if they haven’t changed that, Android 8 should show a notification that app X is using battery, and eventually kill it. Basically the only way to avoid a service being killed is to run it as a foreground service, which means one must show a notification. I can’t imagine Spotify on Android 8 is constantly showing a notification even when not being used for hours or days. It makes clutter. An app should only do so when doing something, like I must do in the next version of the SpotCommander Android app is to always show the now playing notification when the app is open (active or in multitasking), because if not things like “Flip to Pause” will not work. And some dialogue saying why it’s there and just kill SpotCommander to remove it. But I haven’t tried Spotify on Android 8 yet. Maybe Spotify does in fact use the “Ignore optimisations” system choice, and Google doesn’t bother since it’s such a popular app. But they will certainly be strict, as the guidelines say, on apps in general requesting that in code (easy to scan for). You *can* try to manually add Spotify to “Ignore optimisations”, it’s been there since Android 6 but *Doze* as it’s called got more serious in Android 7. I find it under Android Settings > Apps > Overflow menu > Configure apps > Special access > Ignore optimisations.

I can’t see why a PC should disappear as long as the Spotify program is running.
