### ISSUE TITLE
Uninstall fails: rm: cannot remove '/etc/xdg/autostart/spotcommander.desktop': No such file or directory

### ISSUE THREAD

**Issue by endymion1818** [olejon/spotcommander#127]
Installation had previously failed with exist status 1

Using the command in the wiki `sudo apt-get -y purge spotcommander` fails due to the issue below:

`rm: cannot remove '/etc/xdg/autostart/spotcommander.desktop': No such file or directory`

I also tried `apt-get remove spotcommander` previously, without success.

Would be grateful for any assistance.

**Comment by olejon** [comment]
Have you tried to reinstall the deb package then purge it again?

The uninstall script deletes this file without checking that it exists IIRC - that directory is there on any normal distro (I could fix this by running `rm -f` instead of just `rm` on it in the uninstall script. Easier than check it with `if` BASH code. Any not very special distro should have this directory so it should be put in place on install and such possible to remove on uninstall. Would like to know what distro you are running?

If not I suggest you reinstall deb package again. If it did not uninstall correctly I suppose my repository is still added (IIRC it is removed at the end), so run `apt-get —reinstall spotcommander`

Check /etc/xdg/autostart for the file. If it is not there, create it as an empty file, then purge the deb. If even the directory/directories does not exist create them, then afterwards you can delete them, but would be weird.

**Comment by endymion1818** [comment]
Thanks Olejon for the reply, and the update. Unfortunately I did just try this without success. The install script also fails to run. Here is the error message:

```
The following packages will be REMOVED:
  spotcommander
0 upgraded, 0 newly installed, 1 to remove and 12 not upgraded.
1 not fully installed or removed.
After this operation, 5,243 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 275834 files and directories currently installed.)
Removing spotcommander (13.4-1) ...

Stopping daemon...

Backing up playlists and library in case of upgrade...
Backing up authentication configuration in case of upgrade...
Deleting files...
Configuring Apache...
dpkg: error processing package spotcommander (--remove):
 subprocess installed pre-removal script returned error exit status 1
Restoring playlists...
Restoring library...
Restoring authentication configuration...
Setting permissions...
Creating symlink...
Configuring Apache...
dpkg: error while cleaning up:
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 spotcommander
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Really sorry to have to ask again if there's another way you know of removing or supressing this error. I would rather not have to ask but I'm stuck!

**Comment by olejon** [comment]
I have had experienced this several times with “broken packages”, often because an install didn’t go correctly (and you seem to be there now), but it’s annoying because it can screw up APT totally, because of its cache system, if unlucky. Luckily I’ve always been able to fix it by searching. Often the clearing cache first.

```
sudo rm -r /var/lib/dpkg/info/spotcommander.*
sudo apt-get clean
sudo apt-get update
sudo apt-get purge spotcommander

sudo apt-get update
sudo apt-get -f install
sudo apt-get --purge autoremove
sudo dpkg --purge --force-remove-reinstreq spotcommander
```

**Comment by olejon** [comment]
PS: Edited some things above.

**Comment by olejon** [comment]
Some useful tips here as well. Maybe try those two first not so “nuclear” options first.

https://askubuntu.com/questions/438345/how-to-remove-install-a-package-that-is-not-fully-installed/632523

**Comment by endymion1818** [comment]
I followed your steps, apart from the last one (`dpkg`) and tried to reinstall. However, installation failed with message: 

subprocess installed post-installation script returned error exit status 1. 

However, once I went through the process again & removed the files it seems I am back in business. 

Thanks so much for your assistance Olejon.
