### ISSUE TITLE
SOLVED: Ubuntu 18.04 and Spotify 0.9

### ISSUE THREAD

**Issue by Henrytje** [olejon/spotcommander#131]
When installing Spotcommander and spotify 0.9 on ubuntu 18.04 it doesnt work. When opening spotcommander on my android phone is goes straight into a plain text screen with 'this program is free software'. Any chance you are willing to look into this? :) 

Looking forward to your reaction!

**Comment by olejon** [comment]
First of all I asumme you are not a Spotify Premium user since wanting to install Spotify 0.9.

Sorry, after som additional testing I found that installing at least the `libgcrypt` package from Ubuntu 14.04 breaks APT in Ubuntu 18.04 at least. To fix APT one have to uninstall it (and possible the other packages) to be able to use APT to udate repos and upgrade the system.

**SOLUTION:** I will instead download latest package(s) from the Ubuntu 14.04 repo (meaning the security repo), I think only `libgcrypt` is necessary, and extract it and find the neccesary `.so` files needed to run Spotify 0.9, and then put them in my Dropbox so they can be easily downloaded with `wget` and put into place.

**NOTE:** Since these are older versions of the files, *they will not overwrite any newer `.so` files* so the system that depends on the package will continue to use the version for 18.04, only Spotify 0.9 will use the older one.

I will update this when I have done necessary testing and updated the [Wiki page](https://github.com/olejon/spotcommander/wiki/DowngradeSpotify).

**Meanwhile** I suggest you install Spotify 1.0 the Debian package way as [described here](https://github.com/olejon/spotcommander/issues/128), and just live with the downsides with not being a Spotify Premium user, or simply get 1 month of Spotify Premium for free if you have not done so already.

**Comment by olejon** [comment]
**PS:** And make sure you delete `~/.config/spotify` and `~/.cache/spotify` and `~/.local/share/spotify` before updating to Spotity 1.0.

**Comment by olejon** [comment]
I have updated the Wiki page with a new guide that works perfectly in my Ubuntu 18.04 clean and updated virtual machine installation (KVM + QEMU).

* [Guide here](https://github.com/olejon/spotcommander/wiki/DowngradeSpotify) - just a few commands
* I found that the simplest way was to simply repackage Spotify's version that is still in their repository with a modern `control` file with all dependencies added and license etc information from Spotify 1.0 `control` file
* Basically the only legacy thing that needs to be installed is one single file from the `libgcrypt11` package from Ubuntu 14.04 (not included in later versions), and Spotify 0.9 depends of that exact version

**Note:** Remember to uninstall any previous version, be it 0.9 or 1.0. It is Step 1 in the guide. If you have installed the "snap" version, basically if installed Ubuntu Software Center, which is 1.0, you must of course remove it.

If you have any more problems. Please run Spotify from the command line by running `spotify` and look for relevant errors, also post a screenshot.

**Comment by Henrytje** [comment]
Thank you for your rapid comments and solution! Much appreciated

Kind regards, 

A happy user

**Comment by olejon** [comment]
No problem. The previous solution wasn't really a solution anymore (after Ubuntu 18.04 released). I assume it works now but will keep it open for others to see for a while.
