### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by bitmoov** [olejon/spotcommander#76]
Hallo using spotcommander on linux ubuntu 14.04 when I click to Playlist and other functions I got :+1: You must authorize with Spotify . Tap the top right icon to continue

Anyway also with the authorization I got the same issue.

**Comment by olejon** [comment]
What's your Spotify username? If you signed up using Facebook it's a long number.

**Comment by bitmoov** [comment]
Hallo is : bitmoov
Il 31/gen/2015 23:44 "Ole Jon Bjørkum" <notifications@github.com> ha
scritto:

**Comment by olejon** [comment]
OK, so that shouldn't be a problem (no Facebook user, no special characters in username).

I suggest you first try to completely reinstall SpotCommander, like this

```
sudo apt-get update
sudo apt-get -y dist-upgrade
sudo apt-get clean
```

**Reboot**
---

```
sudo apt-get -y purge spotcommander
sudo apt-get -y --purge autoremove
sudo apt-get clean
```

**Reboot**
---

Install SpotCommander from here.
https://github.com/olejon/spotcommander/wiki/Install

Try to authorize now. Try first on the local computer running Spotify. Open a browser, go to `http://localhost/spotcommander` and authorize from there.

Does it work?

If not, check /var/log/apache2/error.log, and look for errors and paste them here.

**Comment by olejon** [comment]
Any progress, or I will close this due to inactivity.

**Comment by bitmoov** [comment]
Hi Ole thank you for the support. I'll try today
Il 03/feb/2015 10:42 "Ole Jon Bjørkum" <notifications@github.com> ha
scritto:

**Comment by olejon** [comment]
Ok, good :)

**Comment by bitmoov** [comment]
Works perfectly. Thank you for your job.
Il 03/feb/2015 10:56 "Ole Jon Bjørkum" <notifications@github.com> ha
scritto:

**Comment by olejon** [comment]
Great :)
