### ISSUE TITLE
Make Spotcommander only available in LAN

### ISSUE THREAD

**Issue by lamarios** [olejon/spotcommander#77]
Is there a way to allow access to spot commander only in my lan network  or, the best of both world, add an htaccess type authentication when accessing from the outside world ?

**Comment by olejon** [comment]
I assume you have opened up ports in your router so that the outside world can reach your webserver right? Otherwise no one outside can access SpotCommander.

What you're asking is certainly possible.

1. First, enbled authentication as described here: https://github.com/olejon/spotcommander/wiki/Authentication

2. Then I need to know your local network IP address range, like 192.168.x.x or 10.x.x.x. You can find it in many ways, check out this: http://www.howtogeek.com/howto/17012/how-to-find-your-ip-address-in-ubuntu/

When you get back to me with that, I can help you so that local clients can access without authenticating.

**Comment by lamarios** [comment]
I enabled the authentication, but it doesn't seem to ask for anything.

My network is  on 192.168.1.0/24.

Thanks.

**Comment by olejon** [comment]
No, you can't do that, but I always recommend not opening port 80 to the outside world. Instead open something like port 8888 and forward it to port 80 on your computer. Otherwise you will see lots of bots scanning your network looking for security holes.

Ok, that's strange. Can you give me the content of `/usr/share/spotcommander/.htaccess` ?

Also, the content of `/etc/apache2/conf-enabled/spotcommander.conf` ?

Also make sure Apache supports auth, run this command

`sudo a2enmod auth_basic`

Then

`sudo service apache2 restart`

**Comment by lamarios** [comment]
Ok, I ran dpkg-reconfigure to reset the settings to default because i played with the conf a bit to try few things.

so now the authentication works, and the conf file is like this:

```
Alias /spotcommander /usr/share/spotcommander

<Directory "/usr/share/spotcommander">
AllowOverride AuthConfig
</Directory>
```

**Comment by olejon** [comment]
I can again, that's good, but you forgot to give me the contents of `/usr/share/spotcommander/.htaccess`

**Comment by lamarios** [comment]
Sorry, my bad. Here it is:
```
AuthType Basic
AuthName "SpotCommander"
AuthBasicProvider file
AuthUserFile /usr/share/spotcommander/bin/../.htpasswd
Require user music
```

**Comment by olejon** [comment]
Ok, replace it with this. File must be opned as root, for example

```
sudo gedit /usr/share/spotcommander/.htaccess
```

Copy, paste and save:

```
AuthType Basic
AuthName "SpotCommander"
AuthBasicProvider file
AuthUserFile /usr/share/spotcommander/bin/../.htpasswd
Require user music

Order deny,allow
Deny from all
Allow from 192.168.1.0/24

Satisfy any
```

Does it work?

**Comment by lamarios** [comment]
Ok, thanks for the help, it seems to work, i was missing the Satisfy any when i tried on my own but i had to add the Limit override to the /etc/apache2/conf-available/spotcommander.conf if not, there was an error that "Order is not allowed here".

```
Alias /spotcommander /usr/share/spotcommander

<Directory "/usr/share/spotcommander">
AllowOverride AuthConfig Limit
</Directory>
```

Thanks for the help, great application !

**Comment by olejon** [comment]
Can you please tell me which distro are you running?

I know that on Arch Linux it won't work if you don't add `Require all granted` after `AuthConfig`. Seems to differ from distro to distro. Note that that is just for auth to work, not with extra rules like yours.

Good to hear that it works.

**Comment by lamarios** [comment]
I'm using ubuntu 14.04.

Yeah, I know it was just for the Auth to work, I just wrote it down in case someone wants the same as me and gets the error too.

**Comment by olejon** [comment]
Would be curious if you could try to replace `Limit ` with `Require all granted`, just to know?

**Comment by lamarios** [comment]
If i remote the Limit and add a Require all granted, I still got the Order not allowed here error. 

But I found out something weird. When the client is using Safari it seems to treat the request as if it's not coming from local network but from outside. Event if i just leave the .htaccess like this: 

```
Order deny,allow
Deny from all
Allow from 192.168.1.0/24
```

Safari will throw a Forbidden error (trying to connect with  my htpc-hostname.local/spotcommander) but works without problems on Chrome. Same on iPhone, using safari, i have forbidden error but not on Chrome.

That is weird.

**Comment by olejon** [comment]
Yeah, check out this:
http://serverfault.com/questions/89984/htaccess-allow-from-hostname

It's a DNS issue. Maybe if you on your **HTPC** add the hostname with the corresponding IP to `/etc/hosts` it'll work.

Something like:

`192.168.1.10 htpc-hostname.local htpc-hostname`

At the end of the file. You should **reboot** after this.

_**Of course change the IP address and hostname to the correct ones**_

**Comment by lamarios** [comment]
Yeah it might, but somehow only happens with Safari client, Chrome on the same machine is not affected… Well it's not very important as I usually use Chrome on desktop and i'll just use the IP of my HTPC for the spring board favourite on my iOs devices.

Anyway, thanks for the great help :)

**Comment by olejon** [comment]
Probably because Safari uses Apple's Bonjour DNS thing before going to regular DNS. So adjusting hosts on your Mac may fix it as well. Let me know if you need help.
