### ISSUE TITLE
Start playlist from selected song

### ISSUE THREAD

**Issue by robin-ambachtsheer** [olejon/spotcommander#78]
Is it possible to implement to begin playing a playlist from a specific song (from the playlist menu)?

Expected behavior:
1. Select playlist
2. Click 'Browse'
3. Select song
4. Click 'Play'
5. When hitting the 'Next' button in the play bar, play the next song in the playlist relative to the above selected song

Right now it would start playing the next song in whatever playlist/queue you were playing before

Thanks for a great app nonetheless :+1:

**Comment by olejon** [comment]
Yes, that's the way Spotify handles playing a URI through D-Bus (because it doesn't associate it with a playlist, because it can be in several playlists).

It's certainly possible to implement the feature you suggest. I would involve playing the playlist URI then immediately playing the song URI. I will look into it in the next version.

In the meantime, you must click the round shuffle play button, or open the top right overflow menu and choose Play, and _then_ play your song.

**Comment by robin-ambachtsheer** [comment]
Thanks for taking a look at this request, much appreciated

**Comment by olejon** [comment]
Yeah, It's certainly a good enhancement. I have another project that is going to be released very soon, so this will be delayed a few weeks, at the most, I hope.

**Comment by olejon** [comment]
Fixed in v 12.4.
